name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Run tests"
        run: fastlane tests
      - name: "Copy results"
        run: cp -r output/*.xcresult output/report.xcresult
      - name: "Generate Allure"
        run: |
          wget https://github.com/eroshenkoam/xcresults/releases/download/1.11.0/xcresults -O ./xcresults && chmod +x ./xcresults
          ./xcresults export output/report.xcresult output/allure-results
